config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #
  root "home#index"

  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :tutor_schedules
  resources :tutors

  get "/home" => "home#index", as: "home"
  get "/student/lessons/schedule-enter" => "schedules#index"
  post "/student/lessons/schedule-enter" => "schedules#create"

  get "/student/lessons/reservation" => "schedules#reservation"
  delete "/student/lessons/reservation" => "schedules#destroy_reservation"

end

app/models/tutor_schedule.rb
class TutorSchedule < ApplicationRecord
  validates :tutor_id, :start_time, :active, :presence => true
  validates :start_time, uniqueness: {scope: [:start_time, :tutor_id]}
  validate :start_date_should_be_future
  belongs_to :tutor

  scope :recent, -> (select_date) { where("start_time >=? AND start_time <=?",
                                          select_date.to_datetime.at_beginning_of_week(start_day = :sunday),
                                          select_date.to_datetime.at_end_of_week(start_day = :sunday) ) }

end

app/controllers/tutor_schedules_controller.rb
class TutorSchedulesController < ApplicationController
  before_action :set_tutor_schedule, only: %i[ show edit update destroy ]

  # GET /tutor_schedules or /tutor_schedules.json
  def index
    @tutor_schedules = TutorSchedule.all
  end

  # GET /tutor_schedules/1 or /tutor_schedules/1.json
  def show
  end

  # GET /tutor_schedules/new
  def new
    @tutor_schedule = TutorSchedule.new
  end

  # GET /tutor_schedules/1/edit
  def edit
  end

  # POST /tutor_schedules or /tutor_schedules.json
  def create
    @tutor_schedule = TutorSchedule.new(tutor_schedule_params)

    respond_to do |format|
      if @tutor_schedule.save
        format.html { redirect_to tutor_schedule_url(@tutor_schedule), notice: "Tutor schedule was successfully created." }
        format.json { render :show, status: :created, location: @tutor_schedule }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tutor_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutor_schedules/1 or /tutor_schedules/1.json
  def update
    respond_to do |format|
      if @tutor_schedule.update(tutor_schedule_params)
        format.html { redirect_to tutor_schedule_url(@tutor_schedule), notice: "Tutor schedule was successfully updated." }
        format.json { render :show, status: :ok, location: @tutor_schedule }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tutor_schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutor_schedules/1 or /tutor_schedules/1.json
  def destroy
    @tutor_schedule.destroy

    respond_to do |format|
      format.html { redirect_to tutor_schedules_url, notice: "Tutor schedule was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor_schedule
      @tutor_schedule = TutorSchedule.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tutor_schedule_params
      params.require(:tutor_schedule).permit(:tutor_id, :start_time, :active)
    end
end

app/helpers/tutor_schedules_helper.rb
module TutorSchedulesHelper
end

app/views/tutor_schedules/_form.html.erb
<%= form_with(model: tutor_schedule) do |form| %>
  <% if tutor_schedule.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tutor_schedule.errors.count, "error") %> prohibited this tutor_schedule from being saved:</h2>

      <ul>
        <% tutor_schedule.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tutor_id, style: "display: block" %>
    <%= form.select :tutor_id, options_for_select(Tutor.all.map{|s|[s.name, s.id]}) %>
  </div>
  <br>
  <div>
    <%= form.label :start_time, style: "display: block" %>
    <%= form.datetime_field :start_time %>
  </div>
  <br>
  <div>
    <%= form.label :active, style: "display: block" %>
    <%= form.text_field :active %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tutor_schedules/_tutor_schedule.html.erb
<div id="<%= dom_id tutor_schedule %>">
<!--  <p>-->
<!--    <strong>Tutor:</strong>-->
    <%#= tutor_schedule.tutor_id %>
<!--  </p>-->

<!--  <p>-->
<!--    <strong>Start time:</strong>-->
    <%#= tutor_schedule.start_time %>
<!--  </p>-->

<!--  <p>-->
<!--    <strong>Active:</strong>-->
    <%#= tutor_schedule.active %>
<!--  </p>-->
  <tr>
    <td><%= tutor_schedule.tutor_id %></td>
    <td><%= tutor_schedule.start_time %></td>
    <td><%= tutor_schedule.active %></td>
    <td><%= link_to "Edit this tutor schedule", edit_tutor_schedule_path(tutor_schedule) %></td>
    <td><%= button_to "Destroy this tutor schedule", tutor_schedule, method: :delete %></td>
<!--    <td><%#= link_to "Show this tutor schedule", tutor_schedule %></td>-->
  </tr>
</div>

app/views/tutor_schedules/edit.html.erb
<h1>Editing tutor schedule</h1>

<%= render "form", tutor_schedule: @tutor_schedule %>

<br>

<div>
  <%= link_to "Show this tutor schedule", @tutor_schedule %> |
  <%= link_to "Back to tutor schedules", tutor_schedules_path %>
</div>

app/views/tutor_schedules/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tutor schedules</h1>

<%= link_to "New tutor schedule", new_tutor_schedule_path %>
<br><br>
<div id="tutor_schedules">
  <table class="bbs_table">
    <thead>
      <tr>
        <td scope="col">Tutor ID</td>
        <td scope="col">Start Time</td>
        <td scope="col">Active</td>
        <td scope="col">Modify</td>
        <td scope="col">Delete</td>
      </tr>
    </thead>
    <tbody>
        <% @tutor_schedules.each do |tutor_schedule| %>
          <%= render tutor_schedule %>
<!--          <p>-->
            <%#= link_to "Show this tutor schedule", tutor_schedule %>
<!--          </p>-->
        <% end %>
    </tbody>
  </table>
</div>

app/views/tutor_schedules/new.html.erb
<h1>New tutor schedule</h1>

<%= render "form", tutor_schedule: @tutor_schedule %>

<br>

<div>
  <%= link_to "Back to tutor schedules", tutor_schedules_path %>
</div>

app/views/tutor_schedules/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tutor_schedule %>

<!--<div>-->
<!--  <%#= link_to "Edit this tutor schedule", edit_tutor_schedule_path(@tutor_schedule) %> |-->
  <%= link_to "Back to tutor schedules", tutor_schedules_path %>

  <%#= button_to "Destroy this tutor schedule", @tutor_schedule, method: :delete %>
<!--</div>-->