config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #
  root "home#index"

  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :tutor_schedules
  resources :tutors

  get "/home" => "home#index", as: "home"
  get "/student/lessons/schedule-enter" => "schedules#index"
  post "/student/lessons/schedule-enter" => "schedules#create"

  get "/student/lessons/reservation" => "schedules#reservation"
  delete "/student/lessons/reservation" => "schedules#destroy_reservation"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseRegistration</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-dark">
      <%= link_to "홈", home_path, class: "navbar-brand home" %>
      <div style="margin-right: 50px; margin-top:10px; margin-bottom: 10px">
        <% if current_user %>
          <%= link_to "로그아웃", destroy_user_session_path, method: :delete, class: "btn-outline-danger"%>
        <% else %>
          <%= link_to "로그인", new_user_session_path, class: "btn btn-outline-danger" %>
          <%= link_to "회원가입", new_user_registration_path, class: "btn btn-outline-danger"%>
        <% end %>
      </div>

    </nav>
    <div class="d-flex align-items-start">
      <% if current_user %>
        <div class="nav flex-column nav-pills me-3" id="v-pills-tab" role="tablist" style="width: 15%" >
          <br>
          <%= link_to "튜터 정보로 이동", tutors_path, class:"nav-link" %>
          <br>
          <%= link_to "수업 스케줄로 이동", tutor_schedules_path, class:"nav-link" %>
          <br>
          <%= link_to "수강신청 하로 가기", student_lessons_schedule_enter_path, class:"nav-link" %>
          <br>
          <%= link_to "예약 정보로 이동", student_lessons_reservation_path, class:"nav-link" %>
          <br>
          <% if current_user.admin? %>
            <br>
            <%= link_to "어드민 페이지로 이동", rails_admin_path, class:"nav-link" %>
          <% end %>
        </div>
      <% end %>
      <div class="ver-line"></div>
      <div class="content" style="width: 85%">
        <%= yield %>
      </div>
    </div>
  </body>
</html>